classes = {
    "Bear": 0,
    "Brown bear": 1,
    "Cheetah": 2,
    "Crocodile": 3,
    "Deer": 4,
    "Elephant": 5,
    "Jaguar": 6,
    "Leopard": 7,
    "Lion": 8,
    "Lizard": 9,
    "Lynx": 10,
    "Panda": 11,
    "Polar bear": 12,
    "Red panda": 13,
    "Rhinoceros": 14,
    "Sea lion": 15,
    "Sea turtle": 16,
    "Shark": 17,
    "Snake": 18,
    "Sparrow": 19,
    "Starfish": 20,
    "Tiger": 21,
    "Tortoise": 22,
    "Turtle": 23,
    "Whale": 24,
    "Zebra": 25,
}
